### ISSUE TITLE
some coalhmm_run_s never end

### ISSUE THREAD

**Issue by yozeng** [rivasiker/autocoalhmm#10]
Hi @rivasiker ,
When I was running autocoalhmm, some of the `coalhmm_run_s` never ended. I first changed the walltime from 6h to 12h, then to 24h, but they still wouldn't end. So I checked the related log file (`coalhmm_run_s.stdout`), and found that all the runs that can't end properly have a repeated `AbstractSubstitutionModel::updateMatrices : Unable to find eigenvector for eigenvalue 0. Taylor series used instead.`, which is not found in other normal runs.
**How should I fix this problem please?**
Following are relevant log files:
log file of an abnormal run:
![coalhmm_run_0 stdout](https://github.com/rivasiker/autocoalhmm/assets/162975460/b9204e07-ac0f-418e-a279-182e6bf5fe67)

log file of a normal run:
![coalhmm_run_1 stdout](https://github.com/rivasiker/autocoalhmm/assets/162975460/769db746-d52d-4b7f-8e95-087a1b5d1b77)

**Comment by rivasiker** [comment]
Hi! I guess I completely missed this issue, sorry! Are you still having problems with this?

**Comment by yozeng** [comment]
Yes, I even extended the time limit to 48 hours, but the problem persists. The way I've handled it so far is to manually filter out the abnormal runs, enabling the software to generate the `final_table.HDF` file, at the expense of losing some locus information.

**Comment by rivasiker** [comment]
It's been a while since I run the pipeline, but I do remember that some of the runs didn't finish in my case neither. I'm guessing it's because of issues with the alignment rather than with the program, but I'm not entirely sure. Since in my case they were very few runs, I simply manually skipped those to generate the final table.

**Comment by yozeng** [comment]
In general, there are very few runs in my case as well. And it sounds like we are using the same solution.
