### ISSUE TITLE
Environment specification is incompatible?

### ISSUE THREAD

**Issue by aabiddanda** [rivasiker/autocoalhmm#3]
Thanks for this great pipeline @rivasiker! I was struggling with the environment setup - since I think that some of the dependencies are incompatible with one another now. I've attached below a log-file as well as an fixed environment that worked for me (and the tests which worked).   Let me know if you would prefer I put in a PR for this as well. 

Otherwise - this pipeline works great - thanks a lot for setting it up! 

[Log File from Original Setup](https://github.com/rivasiker/autocoalhmm/files/12313346/environment.orig.txt)

```
name: primates
channels:
  - conda-forge
  - anaconda
  - gwforg
  - bioconda
  - defaults
dependencies:
  - pip
  - pip:
    - biopython
    - pandas
    - numpy
    - scipy 
    - Cython
    - dask
    - Click
```

**Comment by rivasiker** [comment]
@aabiddanda, thanks for pointing this out! I am currently on vacation, but I will look at it and get back to you as soon as I'm back at work. I'm glad that you made it work, though!

**Comment by aabiddanda** [comment]
Hi @rivasiker just checking that this indeed can be adopted as a fix for your environment? I'm about to start using this a bit more so just wanted to make sure it can be fixed before closing the issue!

**Comment by rivasiker** [comment]
Hi @aabiddanda, and apologies for the delay! I have updated the environment file [through this commit](https://github.com/rivasiker/autocoalhmm/commit/32005a). It now contains a minimal environment, which can be installed through conda. Please, let me know if this works for you! If so, I will close this issue.

**Comment by aabiddanda** [comment]
@rivasiker I can confirm that your updated commit to master works perfectly for me. Happy to close the issue now.
