### ISSUE TITLE
DependencyNeverSatisfied

### ISSUE THREAD

**Issue by AoyueBi** [rivasiker/autocoalhmm#4]
Hi Iker, Recently I have been running the biosoft coalHMM using a small test data. And I would like to ask you some questions about the coalHMM:

1. When I submitted the Python script and used the `queue` command to check my job status, I found that the Nodelist column indicated "**DependencyNeverSatisfied**". During this period, I did not modify the parameters you set for cores=4, memory='16g ', queue='cpu128', walltime='04:00:00 '. I obtained filtered.maf using your script, but in the other method like gwf.target('Start_end'......), no results were obtained. Why?
![WechatIMG48](https://github.com/rivasiker/autocoalhmm/assets/30221313/618db200-1cfc-499f-b781-8956052a4088)

2. How can I modify the code if I don't want to submit a slurm job and instead run the test data locally?

**Comment by rivasiker** [comment]
Hi @AoyueBi!
1. `DependencyNeverSatisfied` probably means that a previous dependency job did not successfully finish, which suggests that there is probably an error when running `Start_end`. In your working directory, can you go to `./tmp/filter/` and run `gwf status`? Can you also run `gwf logs -e Start_end`? This last command will tell you whether any error messages were printed for `Start_end`.
2. You can run the workflow locally by deleting [line 44](https://github.com/rivasiker/autocoalhmm/blob/32005a5781d9615e841b6ae298dcf0471fee4576/autocoalhmm.py#L44C1-L44C62) in `autocoalhmm.py`, and running `gwf workers` in another terminal window before calling `python autocoalhmm.py`. I've never done this, though, so maybe it needs some more tweaking before it actually works. You can take a look at the [gwf documentation](https://gwf.app/guide/tutorial/) for more details.

**Comment by AoyueBi** [comment]
Hi @rivasiker ! 
    So wonderful answers! Thank you so much! The command `gwf logs -e Start_end`  and `gwf status` are useful for me to debug. I may have made many errors due to formatting issues, and I will carefully check them myself next. Thank you!

**Comment by rivasiker** [comment]
@AoyueBi, perfect! Just let me know if you have any more questions.

**Comment by AoyueBi** [comment]
Hi @rivasiker ！
Sorry to disturb you again. Christmas is coming soon, and I guess you might be on vacation already. I have devoted considerable time to running this software, and it has posed some difficulties for me. 

1. In the "test_coalhmm" dir, when I run the workflow.py, I got the result of "inputs_test" with 3 fa file (fasta_0.fa, fasta_0.fa, fasta_0.fa), and "fasta_names_test" with "run_0.txt", "run_1.txt", "run_2.txt", but the dir "info_tables_test" and "outputs_test" were empty. So I use the `gwf logs -e run_0` to check the reason, the log told me that 

> 'DataFrame' object has no attribute 'append'


![image](https://github.com/rivasiker/autocoalhmm/assets/30221313/9fbae452-7bf7-40fc-85e3-445cb075a5de)


2. I check the three fasta file in the "inputs_test" dir, and found that the names after the ">" symbol in the three .fa files are "hg38," "chim," and "chim." In fact, I am conducting ILS (Infinite Sites) calculations for (((hg38 chim) gori) oran). I am puzzled by the generated fasta files.
   
3.  I use command `python ~/biosoft/coalHMM/autocoalhmm.py hg38 chim gori oran hg38.chr21 all.maf.gz > chr21.coalHMM` to run the test data on my cluster. I would like to upload my test file of human chr21 to you, and
    could you help me run the test data on your cluster?  I am confused and don't know where my file format went wrong. Or could you provide some example data for this software? I will be extremely grateful for your help! Due to the limit of file size, I send the test data to your email <irg@birc.au.dk> . Please check it.

Thank you again for your help.

**Comment by rivasiker** [comment]
Hi @AoyueBi!
I am currently running autoCoalHMM with the file you provided me with, and it runs smoothly on my cluster. The generated fasta files in the inputs_test directory have hg38, chim, gori and oran after the ">" symbol. 
- Could you print the contents of the file called `call.txt`? It should be on your working directory.
- Could you then try deleting the `tmp` directory in your working directory, and running `autocoalhmm.py` again?

**Comment by AoyueBi** [comment]
Hi @rivasiker ! 

1. I encountered another issue while running the collect_run step, and I'm unsure how to resolve it. Could you help me?

> Traceback (most recent call last):
  File "/share/home/zhanglab/user/biaoyue/project/ILS/001_analysis/004_coalHMM/tmp/coalhmm/collect_posteriors.py", line 97, in <module>
    pd.concat([pd.DataFrame.from_dict(pos, dtype='int64').reindex(sorted(list(pos.keys())), axis=1).fillna(-1),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/biaoyue/biosoft/anaconda3/envs/ILSgwf/lib/python3.11/site-packages/pandas/core/frame.py", line 1813, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/biaoyue/biosoft/anaconda3/envs/ILSgwf/lib/python3.11/site-packages/pandas/core/frame.py", line 733, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/biaoyue/biosoft/anaconda3/envs/ILSgwf/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/biaoyue/biosoft/anaconda3/envs/ILSgwf/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    arrays, refs = _homogenize(arrays, index, dtype)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/biaoyue/biosoft/anaconda3/envs/ILSgwf/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 629, in _homogenize
    val = sanitize_array(val, index, dtype=dtype, copy=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/biaoyue/biosoft/anaconda3/envs/ILSgwf/lib/python3.11/site-packages/pandas/core/construction.py", line 638, in sanitize_array
    subarr = _try_cast(data, dtype, copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/biaoyue/biosoft/anaconda3/envs/ILSgwf/lib/python3.11/site-packages/pandas/core/construction.py", line 802, in _try_cast
    subarr = maybe_cast_to_integer_array(arr, dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/zhanglab/user/biaoyue/biosoft/anaconda3/envs/ILSgwf/lib/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1619, in maybe_cast_to_integer_array
    casted = np.array(arr, dtype=dtype, copy=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'



2. The call.txt file contains `/share/home/zhanglab/user/biaoyue/biosoft/coalHMM/autocoalhmm.py hg38 chim gori oran hg38.chr21 all.maf.gz`, and everytime when I run autoCoalHMM, I deleted the `tmp` directory and run `autocoalhmm.py` again. It works well! In fact, I made a mistake when I check the `inputs_test` dir. Then I use `seqkit seq -n -i  fasta_0.fa` and found that `The generated fasta files in the inputs_test directory have hg38, chim, gori and oran after the ">" symbol.`
3. I have resolved the issue of 'DataFrame' object has no attribute 'append'. Since my pandas version is 2.1.3, it does not have the `append` method, So I use method `concat` instead. Therefore, I modified your file：In the `test_coalhmm` dir, `create_fasta_and_info_table.py` file, line 84: `df = pd.concat([df, file_df])`， and also In the `coalhmm` dir, `create_fasta_and_info_table.py` file, line 84: `df = pd.concat([df, file_df])`. It wolks well for me.

**Comment by rivasiker** [comment]
Can you make sure you are using the same conda environment as me? Please, copy-paste the following
```
name: autocoalhmm_full
channels:
  - gwforg
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - attrs=23.1.0=pyh71513ae_1
  - biopython=1.79=py37h540881e_2
  - ca-certificates=2023.11.17=hbcca054_0
  - click=8.1.3=py37h89c1867_0
  - click-plugins=1.1.1=py_0
  - gwf=2.0.5=py_0
  - importlib-metadata=4.11.4=py37h89c1867_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libgomp=13.2.0=h807b86a_3
  - liblapack=3.9.0=20_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libsqlite=3.44.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=h59595ed_2
  - numpy=1.21.6=py37h976b520_0
  - openssl=3.2.0=hd590300_1
  - pandas=1.3.5=py37he8f5f7f_0
  - pip=23.3.1=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=4_cp37m
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - setuptools=59.8.0=py37h89c1867_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.44.2=h2c6b66d_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing_extensions=4.7.1=pyha770c72_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zipp=3.15.0=pyhd8ed1ab_0
```
into a file named `environment.yml`. Then, run `conda env create -f environment.yml` to create the environment, activate the environment by running `conda activate autocoalhmm_full`, and then run `autocoalhmm.py` again.

**Comment by AoyueBi** [comment]
Hi @rivasiker !
I believe it might be a version issue causing the occurrence of unexpected bugs. I will retest it according to the environment you provided. Thank you!
