### ISSUE TITLE
Script for analysis the result of coalhmm

### ISSUE THREAD

**Issue by AoyueBi** [rivasiker/autocoalhmm#5]
Hi @rivasiker ,

I used your software to obtain the result of coalhmm, but as I am not very good at Python programming, I do not know how to handle the HDF result. Can you provide me with some useful code to analyze the coalhmm results? I want to view the content of the hdf file, understand the meaning of each line's results, and visualize the ILS distribution of the genome. Can you provide the relevant code? I will be very grateful to you!

(0, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605092, 2097065, 13009126, 6093701)
(1, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605093, 2097066, 13009127, 6093702)
(2, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605094, 2097067, 13009128, 6093703)
(3, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605095, 2097068, 13009129, 6093704)
(4, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605096, 2097069, 13009130, 6093705)
(5, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605097, 2097070, 13009131, 6093706)
(6, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605098, 2097071, 13009132, 6093707)
(7, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605099, 2097072, 13009133, 6093708)
(8, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605100, 2097073, 13009134, 6093709)
(9, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605101, 2097074, 13009135, 6093710)
(10, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605102, 2097075, 13009136, 6093711)
(11, [nan, nan, nan, nan], [b'chr21', b'chr21', b'chr21', b'chr21'], 4605103, 2097076, 13009137, 6093712)
(12, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097078, 13009138, -1)
(13, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097079, 13009139, -1)
(14, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097080, 13009140, -1)
(15, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097081, 13009141, -1)
(16, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097082, 13009142, -1)
(17, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097083, 13009143, -1)
(18, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097084, 13009144, -1)
(19, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097085, 13009145, -1)
(20, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097086, 13009146, -1)
(21, [nan, nan, nan, nan], [b'nan', b'chr21', b'nan', b'chr21'], -1, 2097087, 13009147, -1)
...
...
(1096944, [1., 0., 0., 0.], [b'chr21', b'nan', b'chr21', b'chr21'], 6438482, 61178, -1, 61300)
(1096945, [1., 0., 0., 0.], [b'chr21', b'nan', b'chr21', b'chr21'], 6438483, 61179, -1, 61301)
(1096946, [1., 0., 0., 0.], [b'chr21', b'chr21', b'chr21', b'chr21'], 6438484, 61180, 61252, 61303)
(1096947, [1., 0., 0., 0.], [b'chr21', b'chr21', b'chr21', b'chr21'], 6438485, 61181, 61253, 61304)
(1096948, [1., 0., 0., 0.], [b'chr21', b'chr21', b'chr21', b'chr21'], 6438486, 61182, 61254, 61305)
(1096949, [1., 0., 0., 0.], [b'chr21', b'chr21', b'chr21', b'chr21'], 6438487, 61183, 61255, 61306)

1096949 means position, [1., 0., 0., 0.] means what? [b'chr21', b'chr21', b'chr21', b'chr21'] means chromosome, 6438487, 61183, 61255, 61306 means posteriors？

**Comment by rivasiker** [comment]
If you install `pandas` in `python` and you run `pd.read_hdf('final_table.HDF')`, you will get a table that should look like so:
```
         Ref_species        V0        V1        V2        V3
0           10510000  0.416240  0.085125  0.415258  0.083377
1           10510001  0.416403  0.084855  0.415646  0.083097
2           10510002  0.416561  0.084585  0.416036  0.082817
3           10510003  0.416714  0.084316  0.416430  0.082539
4           10510004  0.416863  0.084048  0.416828  0.082261
...              ...       ...       ...       ...       ...
295417      50805584  0.000459  0.000518  0.000583  0.998440
295418      50805585  0.000589  0.000662  0.000742  0.998006
295419      50805586  0.003388  0.002972  0.003325  0.990315
295420      50805587  0.006160  0.005255  0.005876  0.982709
295421      50805588  0.008905  0.007511  0.008395  0.975188
```
This table contains the coordinate of the reference species and the posterior probabilities of for each of the four hidden states. Please, let me know if you get a similar result.

**Comment by AoyueBi** [comment]
Hi @rivasiker , You are so patient, teaching me how to use these commands.

I use the `pd.read_hdf('final_table.HDF')` and get the similar result you mentioned to me. And then I filtered the lines containing -1 or NA, re stored the data in a txt file, and performed a 100kb sliding window processing using the windowscanr package in R language to obtain the ILS proportion for every 100kb. Finally, the whole genome ILS distribution was plotted using the ggHoriPlot package you wrote. Thanks so much! You have helped me a lot！

Now I want to asked: **1. Do I need to z standardize the data after obtaining ILS proportion (V2+V3/(V0+V1+V2+V3)), as I only analyzed the ILS of (((hg38,chim),gori),oran); in my project?** If true, can you show a clear calculation sample? I was a little puzzled. **2.Do I need to filter the regions with ILS proportion more than the 97.5th quantile?** **3.Do I need to filter the regions with ILS proportion less than 5%?** Because I only analyse the one node, I am not sure to perform the same filtration you mentioned in "Pervasive incomplete lineage sorting illuminates speciation and selection in primates". I apologize for asking so many basic questions. My research foundation is quite weak, but I'm eager to seek clarification on topics that I find challenging to comprehend. Thank you!

I would like share the code with you here:

- 100kb sliding on the genome
```
args <- commandArgs(trailingOnly = TRUE)
input_file <- args[1]
output_file <- args[2]

library(tidyverse)
library(windowscanr)
### 1. 读取文件并去除包含-1或空值的行
df <- read_csv(input_file) %>%
  filter(!any(is.na(.)) & !hg38 == -1)


### 2. 添加HiddenState列
df <- df %>%
  mutate(HiddenState = case_when(
    V0 >= V1 & V0 >= V2 & V0 >= V3 ~ "V0",
    V1 >= V0 & V1 >= V2 & V1 >= V3 ~ "V1",
    V2 >= V0 & V2 >= V1 & V2 >= V3 ~ "V2",
    V3 >= V0 & V3 >= V1 & V3 >= V2 ~ "V3"
  ))

### 3. 进行non-overlap滑窗并统计个数
pos_win <- winScan(x = df,
                   groups = "HiddenState",
                   position = "hg38" ,
                   values = c("HiddenState"),
                   win_size = 100000,
                   win_step = 100000,
                   cores = 2,
                   funs = c("mean", "sd"))

head(pos_win)

df_count <- pos_win %>% 
  pivot_wider(.,names_from = "HiddenState",values_from = "HiddenState_n") %>%
  filter(!(V0 == 0 & V1 == 0 & V2 == 0 & V3 == 0)) %>% 
  select(-win_end,-win_mid,-HiddenState_mean,-HiddenState_sd)
  
write_tsv(df_count,output_file)
```

- Then the Horizon plots was done by this:
```
 library(tidyverse)
 library(ggHoriPlot)
 library(ggthemes)

df <- read_tsv("/Users/Aoyue/Documents/hg38_chr21_window100kb.txt") %>% 
  mutate(ILS = (V2+V3)/(V0+V1+V2+V3))

cutpoints <- df %>% 
  mutate(
    outlier = between(
      ILS,
      quantile(ILS, 0.25, na.rm=T)-
        1.5*IQR(ILS, na.rm=T),
      quantile(ILS, 0.75, na.rm=T)+
        1.5*IQR(ILS, na.rm=T))) %>% 
  filter(outlier)

ori <- sum(range(cutpoints$ILS))/2
sca <- seq(range(cutpoints$ILS)[1], 
           range(cutpoints$ILS)[2], 
           length.out = 7)[-4]

round(ori, 2) # The origin
#> [1] 0.48

round(sca, 2) # The horizon scale cutpoints
#> [1] 0.00 0.16 0.32 0.64 0.80 0.96

p <- df %>% ggplot() +
  geom_horizon(aes(win_start/1000000, 
                   ILS,
                   fill = ..Cutpoints..), 
               origin = ori, horizonscale = sca) +
  scale_fill_hcl(palette = 'RdBu', reverse = T) +
  theme_few() +
  theme(
    panel.spacing.y=unit(0, "lines"),
    legend.position = "none",
    # strip.text.y = element_text(size = 7, angle = 0, hjust = 0),
    axis.text.y = element_blank(),
    # axis.title.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.border = element_blank()
    ) +
  ### 重命名legend的标题
  labs(fill = "ILS proportion")+
  xlab('Position (Mb)') + ylab("Chr21")

ggsave(p,filename = "~/Documents/test.png", width = 4, height = 2)
```

**Comment by rivasiker** [comment]
Great! Answering your questions:
1. You don't need to z-standardize the data in your case. I did it for in our article because we wanted to compare ILS landscapes of different nodes, which have quite varying proportions of ILS. 
2. This is really up to you. In my analyses, it really helped for the visualization to get rid of outlier regions. 
3. You don't need to. In our article, the 5% threshold in the overall proportion of ILS was applied to include only nodes for which we were quite sure that the ILS signal was not spurious.

**Comment by AoyueBi** [comment]
OK! I got it. Sincerely thank you！
