### ISSUE TITLE
autocoalhmm for plant groups

### ISSUE THREAD

**Issue by jjwujay** [rivasiker/autocoalhmm#6]
Hi, @rivasiker 
Could autocoalhmm be used for plant groups?

**Comment by rivasiker** [comment]
It is definitely not restricted to primates, although it would probably need some tweaking of the starting parameters. Alternatively, you can also check our new method called [TRAILS](https://www.biorxiv.org/content/10.1101/2023.06.22.546039v3.full), which is an extension of CoalHMM and is easier to use.

**Comment by rivasiker** [comment]
Closing this issue
